### ISSUE TITLE
RestoreEBSgroup.ps1 volume types

### ISSUE THREAD

**Issue by Vandalay1125** [ferricoxide/WinEBSbackups#1]
Add support for volume types other than "standard" when creating volume from snapshot.

**Comment by ferricoxide** [comment]
Fix pushed with [commit 87f9644](https://github.com/ferricoxide/WinEBSbackups/commit/87f9644ac33dc75402ed2c8f3ba48ca2f82b65fe) enables *basic* run-time selection of volume-type for produced EBS volume-type. Please note the following:
- Default volume-type is still "standard" if no volume type is specified on the command line, created EBSes will be standard/magnetic volumes
- No ratio enforcement for passed iops value is enforced. Any value greater than 100 is allowed. If ratio is exceeded, New-Volume AWS cmdlet will error-out
