### ISSUE TITLE
RestoreEBSgroup.ps1 inline comments missleading

### ISSUE THREAD

**Issue by Vandalay1125** [ferricoxide/WinEBSbackups#2]
Comment says to pass the snapshot group "Name" as a parameter, but script actually expects to match on the tag "Snapshot Group"

**Comment by ferricoxide** [comment]
Closed with commit ID #3c3cc9bd248148b0b8ef6c149e33c4a16c919a6e. Merged back to master with commit ID #a77d0f2c3a3c0b178a68aaa70e7021085ca1cc4e
